package dev._2lstudios.mechanics.listeners.initializers;

import dev._2lstudios.mechanics.listeners.BlockBreakListener;
import dev._2lstudios.mechanics.listeners.BlockDamageListener;
import dev._2lstudios.mechanics.listeners.BlockDispenseListener;
import dev._2lstudios.mechanics.listeners.BlockFromToListener;
import dev._2lstudios.mechanics.listeners.BlockPlaceListener;
import dev._2lstudios.mechanics.listeners.BrewListener;
import dev._2lstudios.mechanics.listeners.ChunkUnloadListener;
import dev._2lstudios.mechanics.listeners.EnchantItemListener;
import dev._2lstudios.mechanics.listeners.EntityDamageByEntityListener;
import dev._2lstudios.mechanics.listeners.EntityDamageListener;
import dev._2lstudios.mechanics.listeners.EntityDeathListener;
import dev._2lstudios.mechanics.listeners.EntityPickupItemListener;
import dev._2lstudios.mechanics.listeners.EntityRegainHealthListener;
import dev._2lstudios.mechanics.listeners.EntitySpawnListener;
import dev._2lstudios.mechanics.listeners.InventoryClickListener;
import dev._2lstudios.mechanics.listeners.InventoryCloseListener;
import dev._2lstudios.mechanics.listeners.InventoryDragListener;
import dev._2lstudios.mechanics.listeners.InventoryMoveListener;
import dev._2lstudios.mechanics.listeners.InventoryOpenListener;
import dev._2lstudios.mechanics.listeners.ItemSpawnListener;
import dev._2lstudios.mechanics.listeners.PlayerDeathListener;
import dev._2lstudios.mechanics.listeners.PlayerFishListener;
import dev._2lstudios.mechanics.listeners.PlayerItemConsumeListener;
import dev._2lstudios.mechanics.listeners.PlayerItemHeldListener;
import dev._2lstudios.mechanics.listeners.PlayerJoinListener;
import dev._2lstudios.mechanics.listeners.PlayerMoveListener;
import dev._2lstudios.mechanics.listeners.PlayerPortalEnterListener;
import dev._2lstudios.mechanics.listeners.PlayerQuitListener;
import dev._2lstudios.mechanics.listeners.PlayerRespawnListener;
import dev._2lstudios.mechanics.listeners.PlayerSwapHandItemsListener;
import dev._2lstudios.mechanics.listeners.PlayerTeleportListener;
import dev._2lstudios.mechanics.listeners.PlayerWorldChangeListener;
import dev._2lstudios.mechanics.listeners.PotionSplashListener;
import dev._2lstudios.mechanics.listeners.PrepareAnvilListener;
import dev._2lstudios.mechanics.listeners.PrepareItemCraftListener;
import dev._2lstudios.mechanics.listeners.ProjectileHitListener;
import dev._2lstudios.mechanics.listeners.ProjectileLaunchListener;
import dev._2lstudios.mechanics.managers.GameMechanicsManager;
import org.bukkit.Server;
import org.bukkit.plugin.Plugin;
import org.bukkit.plugin.PluginManager;

public class MechanicsListeners {
  public static void register(Plugin plugin, GameMechanicsManager gameMechanicsManager) {
    Server server = plugin.getServer();
    PluginManager pluginManager = server.getPluginManager();

    pluginManager.registerEvents(new BlockBreakListener(gameMechanicsManager), plugin);
    pluginManager.registerEvents(new BlockDamageListener(gameMechanicsManager), plugin);
    pluginManager.registerEvents(new BlockDispenseListener(gameMechanicsManager), plugin);
    pluginManager.registerEvents(new BlockFromToListener(), plugin);
    pluginManager.registerEvents(new BlockPlaceListener(gameMechanicsManager), plugin);
    pluginManager.registerEvents(new BrewListener(), plugin);
    pluginManager.registerEvents(new ChunkUnloadListener(), plugin);
    pluginManager.registerEvents(new EnchantItemListener(gameMechanicsManager), plugin);
    pluginManager.registerEvents(new EntityDamageByEntityListener(), plugin);
    pluginManager.registerEvents(new EntityDamageListener(), plugin);
    pluginManager.registerEvents(new EntityDeathListener(), plugin);
    pluginManager.registerEvents(new EntityRegainHealthListener(gameMechanicsManager), plugin);
    pluginManager.registerEvents(new EntitySpawnListener(), plugin);
    pluginManager.registerEvents(new InventoryClickListener(plugin, gameMechanicsManager), plugin);
    pluginManager.registerEvents(new InventoryCloseListener(gameMechanicsManager), plugin);
    pluginManager.registerEvents(new InventoryDragListener(), plugin);
    pluginManager.registerEvents(new InventoryMoveListener(), plugin);
    pluginManager.registerEvents(new InventoryOpenListener(gameMechanicsManager), plugin);
    pluginManager.registerEvents(new ItemSpawnListener(gameMechanicsManager), plugin);
    pluginManager.registerEvents(new PlayerDeathListener(plugin), plugin);
    pluginManager.registerEvents(new PlayerFishListener(), plugin);
    pluginManager.registerEvents(new PlayerItemConsumeListener(), plugin);
    pluginManager.registerEvents(new PlayerItemHeldListener(), plugin);
    pluginManager.registerEvents(new PlayerJoinListener(gameMechanicsManager), plugin);
    pluginManager.registerEvents(new PlayerMoveListener(), plugin);
    pluginManager.registerEvents(new PlayerPortalEnterListener(), plugin);
    pluginManager.registerEvents(new EntityPickupItemListener(gameMechanicsManager), plugin);
    pluginManager.registerEvents(new PlayerQuitListener(gameMechanicsManager), plugin);
    pluginManager.registerEvents(new PlayerRespawnListener(), plugin);
    pluginManager.registerEvents(new PlayerSwapHandItemsListener(), plugin);
    pluginManager.registerEvents(new PlayerTeleportListener(gameMechanicsManager), plugin);
    pluginManager.registerEvents(new PlayerWorldChangeListener(), plugin);
    pluginManager.registerEvents(new PotionSplashListener(), plugin);
    pluginManager.registerEvents(new PrepareAnvilListener(gameMechanicsManager), plugin);
    pluginManager.registerEvents(new PrepareItemCraftListener(gameMechanicsManager), plugin);
    pluginManager.registerEvents(new ProjectileHitListener(server), plugin);
    pluginManager.registerEvents(new ProjectileLaunchListener(), plugin);
  }
}
